from __future__ import annotations


def get_default_element_templates() -> list[dict]:
    return [
        {
            "element_name": "Sales Order Item Demand",
            "source_doctype": "Sales Order Item",
            "item_field": "item_code",
            "company_field": "parent.company",
            "warehouse_field": "warehouse",
            "quantity_field": "qty",
            "date_field": "delivery_date",
            "direction": "Demand",
            "priority": 100,
            "enabled": True,
            "exclusion_behavior": "Record Exclusion",
        },
        {
            "element_name": "Bin Actual Quantity Supply",
            "source_doctype": "Bin",
            "item_field": "item_code",
            "company_field": "",
            "warehouse_field": "warehouse",
            "quantity_field": "actual_qty",
            "date_field": "modified",
            "direction": "Supply",
            "priority": 10,
            "enabled": True,
            "exclusion_behavior": "Record Exclusion",
        },
        {
            "element_name": "Purchase Order Item Supply",
            "source_doctype": "Purchase Order Item",
            "item_field": "item_code",
            "company_field": "parent.company",
            "warehouse_field": "warehouse",
            "quantity_field": "qty",
            "date_field": "schedule_date",
            "direction": "Supply",
            "priority": 30,
            "enabled": True,
            "exclusion_behavior": "Record Exclusion",
        },
        {
            "element_name": "Material Request Item Weak Supply",
            "source_doctype": "Material Request Item",
            "item_field": "item_code",
            "company_field": "parent.company",
            "warehouse_field": "warehouse",
            "quantity_field": "qty",
            "date_field": "schedule_date",
            "direction": "Supply",
            "priority": 60,
            "enabled": False,
            "exclusion_behavior": "Record Exclusion",
            "supply_strength": "weak",
        },
        {
            "element_name": "Work Order Supply",
            "source_doctype": "Work Order",
            "item_field": "production_item",
            "company_field": "company",
            "warehouse_field": "fg_warehouse",
            "quantity_field": "qty",
            "date_field": "planned_end_date",
            "direction": "Supply",
            "priority": 40,
            "enabled": True,
            "exclusion_behavior": "Record Exclusion",
        },
        {
            "element_name": "Work Order Item Component Demand",
            "source_doctype": "Work Order Item",
            "item_field": "item_code",
            "company_field": "parent.company",
            "warehouse_field": "source_warehouse",
            "quantity_field": "required_qty",
            "date_field": "planned_start_date",
            "date_source": "parent_work_order",
            "direction": "Demand",
            "priority": 110,
            "enabled": True,
            "exclusion_behavior": "Record Exclusion",
        },
    ]
