dbfilename redis_queue.rdb
dir /Users/jiantan/ai_assistant/frappe/frappe-bench/config/pids
pidfile /Users/jiantan/ai_assistant/frappe/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

stop-writes-on-bgsave-error no

aclfile /Users/jiantan/ai_assistant/frappe/frappe-bench/config/redis_queue.acl
